/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FriendEmail = IDL.Text;
export const AuthStatus = IDL.Variant({
  'notAuthenticated' : IDL.Null,
  'authenticated' : IDL.Record({ 'email' : IDL.Text }),
});
export const SendResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addFriend' : IDL.Func([FriendEmail], [IDL.Bool], []),
  'getAuthStatus' : IDL.Func([], [AuthStatus], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(FriendEmail)], ['query']),
  'getOAuthUrl' : IDL.Func([], [IDL.Text], []),
  'handleOAuthCallback' : IDL.Func([IDL.Text, IDL.Text], [SendResult], []),
  'removeFriend' : IDL.Func([FriendEmail], [IDL.Bool], []),
  'sendArrivalNotification' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SendResult)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FriendEmail = IDL.Text;
  const AuthStatus = IDL.Variant({
    'notAuthenticated' : IDL.Null,
    'authenticated' : IDL.Record({ 'email' : IDL.Text }),
  });
  const SendResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    'addFriend' : IDL.Func([FriendEmail], [IDL.Bool], []),
    'getAuthStatus' : IDL.Func([], [AuthStatus], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(FriendEmail)], ['query']),
    'getOAuthUrl' : IDL.Func([], [IDL.Text], []),
    'handleOAuthCallback' : IDL.Func([IDL.Text, IDL.Text], [SendResult], []),
    'removeFriend' : IDL.Func([FriendEmail], [IDL.Bool], []),
    'sendArrivalNotification' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SendResult)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };